//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keynan.UnitTests.Example {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExampleConfigurationGroupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleConfigurationGroupResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keynan.UnitTests.Example.ExampleConfigurationGroupResource", typeof(ExampleConfigurationGroupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        public static string EmailContactSetting_Description {
            get {
                return ResourceManager.GetString("EmailContactSetting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Contact.
        /// </summary>
        public static string EmailContactSetting_Name {
            get {
                return ResourceManager.GetString("EmailContactSetting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureA Description.
        /// </summary>
        public static string FeatureA_Description {
            get {
                return ResourceManager.GetString("FeatureA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureA.
        /// </summary>
        public static string FeatureA_Name {
            get {
                return ResourceManager.GetString("FeatureA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the description of the group..
        /// </summary>
        public static string Group_Description {
            get {
                return ResourceManager.GetString("Group_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example Group Name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many videos do you want?.
        /// </summary>
        public static string HowManyVideos_Description {
            get {
                return ResourceManager.GetString("HowManyVideos_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Many Videos?.
        /// </summary>
        public static string HowManyVideos_Name {
            get {
                return ResourceManager.GetString("HowManyVideos_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one these other following items.
        /// </summary>
        public static string PickAnother_Description {
            get {
                return ResourceManager.GetString("PickAnother_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number 1.
        /// </summary>
        public static string PickAnother_ListItem1 {
            get {
                return ResourceManager.GetString("PickAnother_ListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number 2.
        /// </summary>
        public static string PickAnother_ListItem2 {
            get {
                return ResourceManager.GetString("PickAnother_ListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number 3.
        /// </summary>
        public static string PickAnother_ListItem3 {
            get {
                return ResourceManager.GetString("PickAnother_ListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Another.
        /// </summary>
        public static string PickAnother_Name {
            get {
                return ResourceManager.GetString("PickAnother_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one of the following items.
        /// </summary>
        public static string PickOne_Description {
            get {
                return ResourceManager.GetString("PickOne_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #1.
        /// </summary>
        public static string PickOne_ListItem1 {
            get {
                return ResourceManager.GetString("PickOne_ListItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #2.
        /// </summary>
        public static string PickOne_ListItem2 {
            get {
                return ResourceManager.GetString("PickOne_ListItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #3.
        /// </summary>
        public static string PickOne_ListItem3 {
            get {
                return ResourceManager.GetString("PickOne_ListItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick One.
        /// </summary>
        public static string PickOne_Name {
            get {
                return ResourceManager.GetString("PickOne_Name", resourceCulture);
            }
        }
    }
}
